language: r
cache: packages
sudo: required
matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
      env: R_CODECOV=true
env:
   global:
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false
r_packages:
  - devtools
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
warnings_are_errors: true
