# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

time_mat <- function(time) {
    .Call(`_earthtide_time_mat`, time)
}

time_der_mat <- function(time) {
    .Call(`_earthtide_time_der_mat`, time)
}

astro <- function(t_astro, simon, longitude, hours, ddt) {
    .Call(`_earthtide_astro`, t_astro, simon, longitude, hours, ddt)
}

astro_der <- function(t_astro, simon) {
    .Call(`_earthtide_astro_der`, t_astro, simon)
}

legendre_bh <- function(l, m, x, csphase = -1L) {
    .Call(`_earthtide_legendre_bh`, l, m, x, csphase)
}

legendre_deriv_bh <- function(l, m, x) {
    .Call(`_earthtide_legendre_deriv_bh`, l, m, x)
}

scale_legendre_bh <- function(l, m) {
    .Call(`_earthtide_scale_legendre_bh`, l, m)
}

legendre <- function(l_max, x) {
    .Call(`_earthtide_legendre`, l_max, x)
}

et_analyze <- function(astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x0, y0, x1, y1, x2, y2, j2000, o1, resonance, max_amp, update_coef, scale) {
    .Call(`_earthtide_et_analyze`, astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x0, y0, x1, y1, x2, y2, j2000, o1, resonance, max_amp, update_coef, scale)
}

et_predict <- function(astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x0, y0, x1, y1, x2, y2, j2000, o1, resonance, max_amp, update_coef) {
    .Call(`_earthtide_et_predict`, astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x0, y0, x1, y1, x2, y2, j2000, o1, resonance, max_amp, update_coef)
}

et_calculate <- function(astro, astro_der, k_mat, phases, delta, deltar, c0, s0, c1, s1, c2, s2, dgk, jcof, j2000, o1, resonance, index, astro_update, update_coef, magnifier, predict, scale) {
    .Call(`_earthtide_et_calculate`, astro, astro_der, k_mat, phases, delta, deltar, c0, s0, c1, s1, c2, s2, dgk, jcof, j2000, o1, resonance, index, astro_update, update_coef, magnifier, predict, scale)
}

