# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

time_mat <- function(time) {
    .Call(`_earthtide_time_mat`, time)
}

time_der_mat <- function(time) {
    .Call(`_earthtide_time_der_mat`, time)
}

astro <- function(t_astro, simon, longitude, hours, ddt) {
    .Call(`_earthtide_astro`, t_astro, simon, longitude, hours, ddt)
}

astro_der <- function(t_astro, simon) {
    .Call(`_earthtide_astro_der`, t_astro, simon)
}

factorial <- function(x) {
    .Call(`_earthtide_factorial`, x)
}

log_factorial <- function(x) {
    .Call(`_earthtide_log_factorial`, x)
}

scale_legendre <- function(l, m) {
    .Call(`_earthtide_scale_legendre`, l, m)
}

legendre_cpp <- function(l, m, x) {
    .Call(`_earthtide_legendre_cpp`, l, m, x)
}

legendre_deriv_cpp <- function(l, m, x) {
    .Call(`_earthtide_legendre_deriv_cpp`, l, m, x)
}

legendre <- function(l_max, x) {
    .Call(`_earthtide_legendre`, l_max, x)
}

get_catalog_indices <- function(index, ng) {
    .Call(`_earthtide_get_catalog_indices`, index, ng)
}

subset_2_eigen <- function(input) {
    .Call(`_earthtide_subset_2_eigen`, input)
}

subset_eigen <- function(input, subs) {
    .Call(`_earthtide_subset_eigen`, input, subs)
}

unique_eigen <- function(index) {
    .Call(`_earthtide_unique_eigen`, index)
}

calc_dc2 <- function(k_mat, astro, pk, to_rad) {
    .Call(`_earthtide_calc_dc2`, k_mat, astro, pk, to_rad)
}

calc_dc3 <- function(k_mat, astro_der) {
    .Call(`_earthtide_calc_dc3`, k_mat, astro_der)
}

set_fac <- function(body, body_inds, k_mat, astro_der, dc3, delta, deltar, o1, resonance, max_amp) {
    .Call(`_earthtide_set_fac`, body, body_inds, k_mat, astro_der, dc3, delta, deltar, o1, resonance, max_amp)
}

et_analyze_one <- function(astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x, y, j2000, o1, resonance, max_amp, scale) {
    .Call(`_earthtide_et_analyze_one`, astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x, y, j2000, o1, resonance, max_amp, scale)
}

et_predict_one <- function(astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x, y, j2000, o1, resonance, max_amp) {
    .Call(`_earthtide_et_predict_one`, astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x, y, j2000, o1, resonance, max_amp)
}

et_calculate <- function(astro, astro_der, k_mat, phases, delta, deltar, cc, ss, dgk, jcof, j2000, o1, resonance, index, multiplier, predict, scale, n_thread) {
    .Call(`_earthtide_et_calculate`, astro, astro_der, k_mat, phases, delta, deltar, cc, ss, dgk, jcof, j2000, o1, resonance, index, multiplier, predict, scale, n_thread)
}

et_analyze_n <- function(astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x, y, j2000, o1, resonance, max_amp, scale, update_coef) {
    .Call(`_earthtide_et_analyze_n`, astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x, y, j2000, o1, resonance, max_amp, scale, update_coef)
}

et_predict_n <- function(astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x, y, j2000, o1, resonance, max_amp, update_coef) {
    .Call(`_earthtide_et_predict_n`, astro, astro_der, k_mat, pk, body, body_inds, delta, deltar, x, y, j2000, o1, resonance, max_amp, update_coef)
}

et_calculate_n <- function(astro, astro_der, k_mat, phases, delta, deltar, cc, ss, dgk, jcof, j2000, o1, resonance, index, multiplier, predict, scale, n_thread, astro_update, update_coef) {
    .Call(`_earthtide_et_calculate_n`, astro, astro_der, k_mat, phases, delta, deltar, cc, ss, dgk, jcof, j2000, o1, resonance, index, multiplier, predict, scale, n_thread, astro_update, update_coef)
}

